services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: travel-chat-assistant
    ports:
      - "8080:8080"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/travel
    depends_on:
      - mongo

  mongo:
    image: mongo:8.0.14
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
